FROM node:16.13.2-alpine AS builder

ENV NODE_ENV production
WORKDIR /app

COPY package*.json .
RUN npm install
COPY . .

RUN ["npm", "run", "build"]

FROM nginx:1-alpine AS production
COPY --from=builder /app/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD sed -i -e 's/$PORT/'"$PORT"'/g' /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'
